### ISSUE TITLE
Compilation error with newer Cloth Config

### ISSUE THREAD

**Issue by Fourmisain** [Siphalor/tweed-api#16]
I recently cleared out my gradle cache and I can only assume there's been an update to Cloth Config's `TooltipListEntry` as Tweed's [`ClothDropdownSelectEntry`](https://github.com/Siphalor/tweed-api/blob/92f1be904e524315a2e5597f5497815035aaa1e0/src/main/java/de/siphalor/tweed/client/cloth/ClothDropdownSelectEntry.java) now requires method implementations for `get`/`setFocused` and `is`/`setDragging` to compile.

I'm not entirely sure what those methods do, "focused" sounds keyboard input related and "dragging" sounds like it doesn't apply to `ClothDropdownSelectEntry`?

Also, the used `super` constructor
`public TooltipListEntry(Text fieldName, @Nullable Supplier<Optional<Text[]>> tooltipSupplier, boolean requiresRestart)`
has been deprecated.

**Comment by Siphalor** [comment]
Can you specify what branch of Tweed is failing for you with which version of ClothConfig.
The mod is compiling fine for me on CC 4.8.3 and CC 5.0.0.

**Comment by Fourmisain** [comment]
Good question, let's see...

I'm using Tweed branch `v3-1.16` and at least IntelliJ lists
`Gradle: me.shedaniel.cloth:config-2:4.8.3@net.fabricmc.yarn.1_16_4.1.16.4+build.1-v2`

So I don't really know why it's failing...
Looking through [Cloth Configs repo](https://github.com/shedaniel/cloth-config) I can't even find any reference to an abstract method `setFocused()` - what is even going on?

**Comment by Fourmisain** [comment]
Okay, I just removed all untracked files from tweed an now it's building like it should!
I can't grasp what gradle does sometimes...
False alarm, sorry about that!

**Comment by Siphalor** [comment]
No problem ;)

**Comment by Fourmisain** [comment]
Aha!
That also fixed the testmod startup crash I've been getting
