### ISSUE TITLE
Crash involving another mod (Extra Pieces).

### ISSUE THREAD

**Issue by Rahmiel** [Siphalor/tweed-api#4]
I originally posted this on Extra Pieces, but they can't seem to find the issue directly. Wanted to post this here as well. All links to crash logs and information can be found in the original issue here:

https://github.com/Shnupbups/extra-pieces/issues/11

**Comment by Siphalor** [comment]
This is gone.
Mouse Wheelie is still crashing with Extra Pieces but that's another bug ;)

**Comment by Siphalor** [comment]
Okay this bug appeared again.
Quick note it works with Extra Pieces v1.3.0 or below.

**Comment by Siphalor** [comment]
Ok, seems to work now again. lol
