### ISSUE TITLE
Crash When Configuring via Mod Menu

### ISSUE THREAD

**Issue by jkat718** [Siphalor/tweed-api#9]
When I use the "configure..." button in Mod Menu for either Tweed or MouseWheelie, the game crashes (report below). I initially thought it was an issue with Mouse Wheelie, since that was the only mod that was causing crashes, but when I unfiltered libraries from the mod list, I realized it was also happening with Tweed. I'm assuming the issue is with Tweed, rather than MouseWheelie, but IDK. MouseWheelie seems to be working fine otherwise, so thank you for that!

[Crash Report - Pastebin](https://pastebin.com/VjEea6yH)

MC Version: 1.16.2
Fabric Loader Version: 0.9.1+build.205
Fabric API Version: 0.17.2+build.396

Mods:
VoxelMap 1.10.10
MaLiLib 0.10.0
MiniHud 0.19.0
ModMenu 1.14.6
MouseWheelie 1.5.1

**Comment by jkat718** [comment]
And this time, it's not an issue of me manually downloading Tweed when I wasn't supposed to, lol. (Sorry again for that!)

**Comment by Siphalor** [comment]
At first, sorry for the late response.
This issue looks a lot like a specific build of Mouse Wheelie used an outdated version of ClothConfig.
I expect the issue to have resolved on its own but just to be sure please reply if you're still experiencing this crash in the latest release.

**Comment by jkat718** [comment]
Yep, looks like it did resolve on its own!
